google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}
  pubSub:
    topic: java-competency
    subscriptionId: java-competency-sub
    projectId: oval-crawler-398007
    credentials: oval-crawler-398007-576558a953e4.json
  elastic:
    indexName: car-details
    host: 35.201.207.148
    port: 9200
spring:
  cloud:
    gcp:
      project-id: white-dynamo-394708

apiUrl: /vehicle.json?key=45d8b3f0
mockaroo:
  api:
    url: https://my.api.mockaroo.com