google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}
  pubSub:
    topic: Vehicle
spring:
  cloud:
    gcp:
      project-id: sustained-digit-399111

apiUrl: /vehicle.json?key=45d8b3f0
mockaroo:
  api:
    url: https://my.api.mockaroo.com
