cosmosdb:
  key: ${COSMOS_KEY}
  uri: ${COSMOS_URI}
spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    properties:
      security.protocol: ${PROTOCOL}
      sasl.mechanism: ${MECHANISM}
      sasl.jaas.config: ${CONFIG}
    producer:
      key-serializer: ${KEY_SERIALIZER}
      value-serializer: ${JSON_SERIALIZER}
mockaroo:
  api:
    url: https://my.api.mockaroo.com
apiUrl: /vehicle.json?key=45d8b3f0
