cosmosdb:
  key: ${COSMOS_KEY}
  uri: ${COSMOS_URI}

spring:
  autoconfigure:
    exclude: com.google.cloud.spring.autoconfigure.firestore.FirestoreRepositoriesAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
      sasl.mechanism: ${SASL_MECHANISM}
      sasl.jaas.config: ${JASS_CONFIG}
    producer:
      key-serializer: ${KEY_SERIALIZER}
      value-serializer: ${VALUE_SERIALIZER}
