google:
  application:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS}
  pubSub:
    topic: ${PUB_SUB_TOPIC_ID}
spring:
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID}

apiUrl: /model_random.json?key=dcbc8750
mockaroo:
  api:
    url: https://my.api.mockaroo.com
