apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-competency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-competency-demo
  template:
    metadata:
      labels:
        app: java-competency-demo
    spec:
      containers:
        - name: java-competency-demo
          image: ghcr.io/vimal-knoldus/az-nashtech-demo-app:${{ github.sha }}
          env:
            - name: COSMOS_KEY
              value: ${{ secrets.COSMOS_KEY }}
            - name: COSMOS_URI
              value: ${{ secrets.COSMOS_URI }}
            - name: KAFKA_SERVER
              value: ${{ secrets.KAFKA_SERVER }}
            - name: KAFKA_SECURITY_PROTOCOL
              value: ${{ secrets.KAFKA_SECURITY_PROTOCOL }}
            - name: SASL_MECHANISM
              value: ${{ secrets.SASL_MECHANISM }}
            - name: JASS_CONFIG
              value: ${{ secrets.JASS_CONFIG }}
            - name: KEY_SERIALIZER
              value: ${{ secrets.KEY_SERIALIZER }}
            - name: VALUE_SERIALIZER
              value: ${{ secrets.VALUE_SERIALIZER }}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-az-secret-6
