apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-competency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-competency-demo
  template:
    metadata:
      labels:
        app: java-competency-demo
    spec:
      containers:
        - name: java-competency-demo
          image: ghcr.io/vimal-knoldus/az-nashtech-demo-app:${{ github.sha }}
          env:
            - name: COSMOS_KEY
              value: uyZNCODa8FDmBd3lMDFCw0ADJtR9D5HDBbNKpSz0rktVmN4khFIXmwyxnEbYY10nKaQZZzoGawO1ACDbmVKvuw==
            - name: COSMOS_URI
              value: https://azure-car-factory-db.documents.azure.com:443/
            - name: KAFKA_SERVER
              value: myNamespace2023125.servicebus.windows.net:9093
            - name: KAFKA_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: SASL_MECHANISM
              value: PLAIN
            - name: JASS_CONFIG
              value: CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://mynamespace2023125.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=waqRW0PFooNb9rTAyA5uoLRiHzc9IPsyH+AEhLQX/wk=";
            - name: KEY_SERIALIZER
              value: org.springframework.kafka.support.serializer.StringOrBytesSerializer
            - name: VALUE_SERIALIZER
              value: org.springframework.kafka.support.serializer.JsonSerializer
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAid2hpdGUtZHluYW1vLTM5NDcwOCIsCiAgInByaXZhdGVfa2V5X2lkIjogIjQxZWRmNzk4ZTkzOGQ3ODE5NjhhMTIyZDkxMzkwMDVmYzcyM2Q1OWMiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQzNxVE9iN252WEY0T0Rcbk9KbHBPUXNVUWplcGorQUpjUHB5MWQxT05JV2JBWUJ4Q3RNVEpFMzBQL3kyTnNEK2J6QjdVTEhpa3U4blA3OFFcbnVwWDhGbmJvbjlhZGZHZXNDd05OcGlTeDFtYktMTHB1cHkvUXd2ZmphUFl3M2RnNW5wZHQ4ekdTYzFlTDA1SDJcbjBNbHBDUDhUcTBwdlUrenJ4Y3NtaTcrbS9SMkYzOWx4U2tqbHI1Z0FmMkRxc3QreUZYZlQ5dC9Pd3BzeTBWU1NcbkM0KzIyMFpiVVhqZFcyakpYK2FlV0FpSGJ1aTZKSGJtR1doUXZXMkhHVlByK2NpTFl5WStwd2tCZkc3MjI5WXpcbmNucGxYZlVrWVZNYTdReHdnSkxRRjdXYVJVM1NDZ0IzVzN6ZGpVVW5YK3o5eVhEbVZKcStGVjRKdlplSVJNQWRcblhXN2NuSG0xQWdNQkFBRUNnZ0VBQlFDcU1GSS9VR21tNGtrK1lybzdRejhkS1FaU2M2OWlIM1l3dVRjTmVDVm1cbmpEdnRzTTNKZGowTVpPbFBqeDZpYjZlc2w5aHdTNlM1aUVJQ0o5azdCVU9JMitLallTcEt2V2kycmRRUWk4OERcbnBCc1FYcFIwZ2Q3TWV6N3ZzbUJQdUJDSEZIbnBKYXI4aE5XbzFRUFBSZm1vckVWblpLcmtrSlZVa0RDSDZ1UC9cbnNLV3hzbWU5RExzMjNSaFlmVXphd0pyTmNlK0RhMEtJNGNNMmgxSlV2RkExenM4U1J0SnduUnB3VGp4ak9DdG9cbmxxWHdBUEpvY1FRZHUyU01zRWQ4aGZmWHNvZUhKWkhtVHhqOVZrbHZ5Ump3VWcySitaMHg4VTA5b3lJNzVIZFFcbmlFeUtacyt5TVNLTjRJUFdNeWZHY0Rjdm9PNStpL1FQQk1QL2gyNS9nUUtCZ1FEMFZtMVJDcHoyTVUxVER5QTFcbkFTZnR5QXZhZEJsL04yQzJhTWY0UlhKc2c2UzJiVDFYbnhneENCb3hVSXJ4U3VvR3h0R2g0ZWFmcUJXTnRrSHhcbnhuck9aL1hCcEorelRaRFlQMmg3SDNDSVc0MXZLUDFqQnBxSUEvSmtiOE4rVytJenMzd1gxUUFHR1Rscm9MTU5cbk1QK2QwTkJ6ZENEOUFkK1E1b25nVGRtWGNRS0JnUURBYlYwUDd5S2svaG1hOVlnZE5yWGpwSkdHNDdlYlAvYkRcbm1KRTJwVE05Wnl1MDErSC9udkdWK1oyNDZBTVZxVnl1L1oyUlByam5ValFMSGNhOTQzSEZ6TEp4TDBZYTR1dW9cbm9DcUJKVWRZK3pRZkMrVzIrOUR4N3JaNG1QTTErbFVaNlJtOXVJdzF5akgrQWV1MTZoUDRmNW1Fam14MkdVbEJcbmM4WEhmaStNaFFLQmdRQ2wvQ1NOSG1HYzJjZEd1b3JObHpoeHp5bEdRUUtsS3BDWHVqekdpeDc5V3J6RmRSWnJcbjlOY3hUK2pEUVl6eCtFdGRTU2xXQ0tsc0lucHA1N3VLcktQMm5pY1VZbXBmR3oxZnVrdVhBTGVvMmxFTmg5SUNcbnVKUzMrNzVwdm9jV3l3S3l6cVpwWmpoNjdCM1c0TGRpS2J3c2tKTmJLelBSekxqOHJiQlNZWENFOFFLQmdRQ0lcbnV5MHRiVmJJdG1XclhseGhwY2FKQXg4Rklqb003dDZCRFovaG5IRlVhRUwrTllnNUFzL1hLWStSSEF0VkVRcnlcbnJQT1JpV2dKdHJlVVRvd3gwYk8rUVQxcWY1VG85ZVZONU1GUEV4WW5mQmdGRjRjYkJzUHBwUjJ6ZzdzTjE5c3dcbmxobmNYWTREaXJFTE5JSXd1U3VIbitPTjlVWE1oUnN3anZzeVRjK3JvUUtCZ1FESlFia2x4Y2FkQ2E0MzFOVnRcbi9lWk5ZaE8vZldxWlgvZDE0Q0pPSWRjM3MvcnZObTZlL2xjODJaUDdZdk51OTJJVFQrbVpYKzUyVVBmM1FTTGRcbnVoSlVEZHY5d2g2Qm5BZ0JvVng0TXQzN0QydHJNYzA2eHNTRSs1bGtIS05FeGlIeUZTcDZxVVhhcTB0WnlZQTdcbldSa0RoL3BrbmtxakdUNnZ1SGkya3pjWFVnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICIyNjM1NDA0Njc2MTUtY29tcHV0ZUBkZXZlbG9wZXIuZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDQwMTY3ODc0NzIwNzg4NjQ4ODgiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5LzI2MzU0MDQ2NzYxNS1jb21wdXRlJTQwZGV2ZWxvcGVyLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K

          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ghcr-az-secret-2
