apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-demo-app
  template:
    metadata:
      labels:
        app: gcp-demo-app
    spec:
      containers:
        - name: gcp-demo-app
          image: us-central1-docker.pkg.dev/${{env.PROJECT_ID}}/gcp-demo-app/gcp-deployment
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: java-competency-configmap
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-demo-app-service
spec:
  selector:
    app: gcp-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: java-competency-configmap
data:
  # Configuration values can be set as key-value properties
  GCP_PROJECT_ID: ${{env.PROJECT_ID}}
  PUB_SUB_TOPIC_ID: ${{env.PUB_SUB_TOPIC_ID}}
