name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/vimal-knoldus/az-nashtech-demo-app
  AKS_CLUSTER: az-nashtech-cluster
  AKS_NAMESPACE: default
  COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
  COSMOS_URI: ${{ secrets.COSMOS_URI }}
  KAFKA_SERVER: ${{ secrets.KAFKA_SERVER }}
  KAFKA_SECURITY_PROTOCOL: ${{ secrets.KAFKA_SECURITY_PROTOCOL }}
  SASL_MECHANISM: ${{ secrets.SASL_MECHANISM }}
  JASS_CONFIG: ${{ secrets.JASS_CONFIG }}
  KEY_SERIALIZER: ${{ secrets.KEY_SERIALIZER }}
  VALUE_SERIALIZER: ${{ secrets.VALUE_SERIALIZER }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      - name: Log in to GitHub Artifact Registry
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u vimal-knoldus --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ env.IMAGE_NAME }}:${{ github.sha }}" .
          docker push "${{ env.IMAGE_NAME }}:${{ github.sha }}"

      - name: Configure Kubernetes environment
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: az-nashtech-cluster
          resource-group: rgNtDemo

      - name: Create image pull secret
        run: |
          kubectl create secret docker-registry ghcr-az-secret-6 --docker-server=ghcr.io --docker-username=vimal-knoldus --docker-password="${{ secrets.TOKEN_GITHUB }}" --namespace=${{ env.AKS_NAMESPACE }}

      - name: List Manifests Directory
        run: ls manifests

      - name: Apply Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: ${IMAGE_NAME}:${{ github.sha }}|g" manifests/deployment.yml
          kubectl apply -f manifests/deployment.yml --namespace ${{ env.AKS_NAMESPACE }}
          kubectl apply -f manifests/service.yml --namespace ${{ env.AKS_NAMESPACE }}
