name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcp-demo-app/gcp-deployment
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GCP_CLUSTER_NAME }}
  GKE_ZONE: us-central1

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: java-competency-demo-0.0.1-SNAPSHOT.jar
          path: target/

  build-docker-image:
    name: Build Docker
    needs: setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
          name: java-competency-demo-0.0.1-SNAPSHOT.jar
          path: target/
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '>= 446.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          export_default_credentials: true
      - name: Configure Docker for Google Cloud Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Build and push Docker image to Artifact Registry
        run: |
          docker build --tag $IMAGE_NAME .
          docker push $IMAGE_NAME          

  deploy-to-gke:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLUSTER_NAME: ${{ secrets.GCP_CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/